const GET_DEPARTMENT_LIST = 'printdesk/GET_DEPARTMENT_LIST';
const GET_DEPARTMENT_LIST_SUCCESS = 'printdesk/GET_DEPARTMENT_LIST_SUCCESS';
const GET_DEPARTMENT_LIST_ERROR = 'printdesk/GET_DEPARTMENT_LIST_ERROR';

const ADD_DEPARTMENT = 'printdesk/ADD_DEPARTMENT';
const ADD_DEPARTMENT_SUCCESS = 'printdesk/ADD_DEPARTMENT_SUCCESS';
const ADD_DEPARTMENT_ERROR = 'printdesk/ADD_DEPARTMENT_ERROR';

export {
  GET_DEPARTMENT_LIST,
  GET_DEPARTMENT_LIST_SUCCESS,
  GET_DEPARTMENT_LIST_ERROR,
  ADD_DEPARTMENT,
  ADD_DEPARTMENT_SUCCESS,
  ADD_DEPARTMENT_ERROR,
};
