const GET_MENU = 'printdesk/GET_MENU';
const GET_MENU_SUCCESS = 'printdesk/GET_MENU_SUCCESS';
const GET_MENU_ERROR = 'printdesk/GET_MENU_ERROR';

const MENU_CLICK_MOBILE_MENU = 'printdesk/MENU_CLICK_MOBILE_MENU';
const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  'printdesk/MENU_CHANGE_HAS_SUB_ITEM_STATUS';
const MENU_SET_CLASSNAMES = 'printdesk/MENU_SET_CLASSNAMES';
const MENU_CONTAINER_ADD_CLASSNAME = 'printdesk/MENU_CONTAINER_ADD_CLASSNAME';

export {
  GET_MENU,
  GET_MENU_SUCCESS,
  GET_MENU_ERROR,
  MENU_CLICK_MOBILE_MENU,
  MENU_CHANGE_HAS_SUB_ITEM_STATUS,
  MENU_SET_CLASSNAMES,
  MENU_CONTAINER_ADD_CLASSNAME,
};
