spring:
  profiles:
    active: dev
    include: oauth

---

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/printko?characterEncoding=UTF8&serverTimezone=Asia/Seoul
    username: printko
    password: printko_@KOREA2017

  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  config:
    activate:
      on-profile: dev

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  port: 8081

---

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/print2?serverTimezone=Asia/Seoul
#    username: root
#    password: tlsgudtjq1!
#
#  jpa:
#    open-in-view: false
#    show-sql: true
#    generate-ddl: true
#  config:
#    activate:
#      on-profile: prod
#
#server:
#  port: 8082